# all images will be resized to that
target_size_x: 1024
target_size_y: 1360

batch_size: 16
num_workers: 4

learning_rate: 0.0001

num_epochs: 100

cometml_tag: cell_nuclei_segmentation

device: cuda:5

cometml_name: first_run_gpu


